version: "3.9"
services:
  client:
    build: "./client"
    ports:
      - "3001:3001"
    volumes:
      - "./client:/app/client"
      - "/app/client/node_modules"
      - "./shared:/app/shared"
    depends_on:
      - "server"
  server:
    build: "./server"
    ports:
      - "3000:3000"
    volumes:
      - "./server:/app/server"
      - "/app/server/node_modules"
      - "./shared:/app/shared"
