export const SOCKET_SPAWN_PLAYER = "SOCKET_SPAWN_PLAYER";
export const SOCKET_UPDATE_POSITIONS = "SOCKET_UPDATE_POSITIONS";
export const SOCKET_UPDATE_USER_POS = "SOCKET_UPDATE_POSITION";
export const SOCKET_GET_CURRENT_PLAYERS = "SOCKET_GET_CURRENT_PLAYERS";
export const SOCKET_GET_PICKUPS = "SOCKET_GET_PICKUPS";
export const SOCKET_SET_PICKUPS = "SOCKET_SET_PICKUPS";
export const SOCKET_UPDATE_PICKUP = "SOCKET_UPDATE_PICKUP";
